### ISSUE TITLE
혹시 사용하셨을 때 openjdk를 사용하셨었나요?

### ISSUE THREAD

**Issue by audtjddld** [LeeKyoungIl/webp-java-sample#1]
openjdk에서는 jpg 라이브러리 이슈가 있던거 같아서 여쭤봅니다.

**Comment by LeeKyoungIl** [comment]
@audtjddld

안녕하세요. 코멘트를 늦게 봐서 죄송합니다.
한참전에 작업 했던거라 ^^;

당시 hotspot jvm 사용 했습니다. 아마 1.6,7,8 에서 테스트 했을껍니다. 이상 없었고 openjdk에서는 테스트 하지 못했어요!

**Comment by audtjddld** [comment]
webp 관련 처리가 있었는데 공유해주신 코드 보며 잘 해결했습니다.

openjdk에서는 jpeg 라이브러리가 빠져있어서 애를 먹었었는데 그것도 포함해서 여쭤봤었습니다. ㅎㅎ

답변 감사합니다.
